export const dummy_data = {
  arabicLabel: "مدير",
  englishLabel: "Manager",
  id: 3,
  key: 3,
  parents: [],
  children: [
    {
      arabicLabel: "موظف",
      englishLabel: "Employee",
      id: 2,
      key: 2,
      parents: [],
      children: [
        {
          arabicLabel: "2موظف",
          englishLabel: "Employee2",
          id: 5,
          key: 5,
          parents: [],
          children: [
            {
              arabicLabel: "3موظف",
              englishLabel: "Employee4",
              id: 6,
              key: 6,
              parents: [],
            },
            {
              arabicLabel: "3موظف",
              englishLabel: "Employee4",
              id: 6,
              key: 6,
              parents: [],
            },
            {
              arabicLabel: "3موظف",
              englishLabel: "Employee4",
              id: 6,
              key: 6,
              parents: [],
            },
            {
              arabicLabel: "3موظف",
              englishLabel: "Employee4",
              id: 6,
              key: 6,
              parents: [],
            },
            {
              arabicLabel: "3موظف",
              englishLabel: "Employee4",
              id: 6,
              key: 6,
              parents: [],
              children: [
                {
                  arabicLabel: "3موظف",
                  englishLabel: "Employee4",
                  id: 6,
                  key: 6,
                  parents: [],
                  children: [
                    {
                      arabicLabel: "3موظف",
                      englishLabel: "Employee4",
                      id: 6,
                      key: 6,
                      parents: [],
                      children: [
                        {
                          arabicLabel: "3موظف",
                          englishLabel: "Employee4",
                          id: 6,
                          key: 6,
                          parents: [],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 1,
      key: 1,
      parents: [],
      children: [
        {
          arabicLabel: "3موظف",
          englishLabel: "Employee4",
          id: 6,
          key: 6,
          parents: [],
        },
      ],
      arabicLabel: "تيست",
      englishLabel: "test",
    },
    {
      id: 1,
      key: 1,
      parents: [],
      children: [
        {
          arabicLabel: "5موظف",
          englishLabel: "Employee5",
          id: 6,
          key: 6,
          parents: [],
        },
        {
          arabicLabel: "6موظف",
          englishLabel: "Employee6",
          id: 6,
          key: 6,
          parents: [],
        },
        {
          arabicLabel: "7موظف",
          englishLabel: "Employee7",
          id: 6,
          key: 6,
          parents: [],
        },
      ],
      arabicLabel: "2تيست",
      englishLabel: "test2",
    },
    {
      id: 1,
      key: 1,
      parents: [],
      children: [
        {
          arabicLabel: "7موظف",
          englishLabel: "Employee7",
          id: 6,
          key: 6,
          parents: [],
        },
      ],
      arabicLabel: "2تيست",
      englishLabel: "test2",
    },
    {
      id: 1,
      key: 1,
      parents: [],
      children: [
        {
          arabicLabel: "5موظف",
          englishLabel: "Employee5",
          id: 6,
          key: 6,
          parents: [],
          children: [
            {
              id: 1,
              key: 1,
              parents: [],
              children: [],
              arabicLabel: "hamo",
              englishLabel: "hamo",
            },
          ],
        },
        {
          arabicLabel: "6موظف",
          englishLabel: "Employee6",
          id: 6,
          key: 6,
          parents: [],
        },
        {
          arabicLabel: "7موظف",
          englishLabel: "Employee7",
          id: 6,
          key: 6,
          parents: [],
        },
      ],
      arabicLabel: "hamo",
      englishLabel: "hamo",
    },
  ],
};
